# Generated by Django 4.2.21 on 2025-05-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cityquerystats", old_name="name", new_name="user_input",
        ),
        migrations.AddField(
            model_name="cityquerystats",
            name="normalized_name",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="cityquerystats", unique_together={("user_input", "normalized_name")},
        ),
    ]
